### PR TITLE
Update ttcli.rbs

### PR DESCRIPTION
**Pull request by openworker**
added linux support.

### CODE REVIEW

**Comment by wimdeblauwe** [comment]
Thank you for your contribution. I am just wondering if this change should be done directly here, because this repo is handled automatically by JReleaser from https://github.com/wimdeblauwe/ttcli

**Comment by openworker** [comment]
Ah.  I see.  My pleasure. I came across the issue while reading your excellent HTMX book and working with WSL2 Ubuntu.  Thank you for the insight regarding jreleaser!  I haven't used it before.  Great work Wim.

**Comment by wimdeblauwe** [comment]
So ttcli is not available currently on linux via homebrew then?

**Comment by openworker** [comment]
No it isn't.  When I ran "brew install wimdeblauwe/homebrew-ttcli/ttcli", I got an error: "Error: formulae require at least a URL".  

When I looked into why, I noticed that while there were linux binaries in the release assets, the code generated from jrelease in homebrew-ttcli ony defined formulas for mac arm / mac intel.      Adding the linux conditions and asset / sha256 references resolved the error for me.

**Comment by wimdeblauwe** [comment]
Ok, I asked the JReleaser team now how to best fix it: https://github.com/jreleaser/jreleaser/discussions/1593

**Comment by wimdeblauwe** [comment]
I just released version 1.1.2, which should now bring Linux support.

**Comment by openworker** [comment]
Great! Thanks Wim.

**Pull request closed without merging**
